version: '3'
services:
  api:
    build: ./api
    tty: true
    working_dir: "${HOME}"
    user: "${UID}:${GID}"
    command: "node"
    ports:
      - 3000:3000
    volumes:
      - "./api:${HOME}/api"
  client:
    build: ./client
    tty: true
    working_dir: "${HOME}"
    user: "${UID}:${GID}"
    command: "node"
    ports:
      - 3001:3001
    volumes:
      - "./client:${HOME}/client"
  admin:
    build: ./admin
    tty: true
    working_dir: "${HOME}"
    user: "${UID}:${GID}"
    command: "node"
    ports:
      - 3002:3002
    volumes:
      - "./admin:${HOME}/admin"
